import { beforeEach, describe, expect, it, vi } from "vitest";

const dbMocks = { getBusinessUser: vi.fn(), getOverview: vi.fn(), normalizePeriod: vi.fn((value: string) => value === "Agosto de 2026" ? "2026-08" : value), createAbsence: vi.fn(), createSubmission: vi.fn(), listSubmissions: vi.fn(), reviewSubmission: vi.fn(), getSchoolByName: vi.fn(), confirmStudentImport: vi.fn() };
vi.mock("./db", () => ({ ...dbMocks }));
const { appRouter } = await import("./routers");

const context = (role: "admin" | "user", id = 1) => ({ user: { id, openId: `${id}`, name: "Teste", email: "teste@example.com", loginMethod: "test", role, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: {} as any, res: {} as any });

describe("business flows", () => {
  beforeEach(() => { vi.clearAllMocks(); dbMocks.getBusinessUser.mockResolvedValue({ id: 88, perfil: "ADMIN", escolaId: null, ativo: 1 }); dbMocks.normalizePeriod.mockImplementation((value: string) => value === "Agosto de 2026" ? "2026-08" : value); dbMocks.createAbsence.mockResolvedValue(44); dbMocks.createSubmission.mockResolvedValue(55); dbMocks.listSubmissions.mockResolvedValue([{ id: 55, escolaId: 2, periodo: "Agosto de 2026", status: "ENVIADO", enviadoEm: new Date(), escola: "CEI LUIZ FELIPE" }]); dbMocks.reviewSubmission.mockResolvedValue({}); dbMocks.getSchoolByName.mockResolvedValue({ id: 2, nome: "CEI LUIZ FELIPE" }); dbMocks.confirmStudentImport.mockResolvedValue({ inserted: 1, skipped: 0 }); });
  it("creates an absence as a draft with the validated payload", async () => { const result = await appRouter.createCaller(context("admin")).absences.create({ alunoId: 7, escolaId: 2, dataFalta: "2026-08-26", quantidadeDias: 2, motivo: "Doença", observacao: "Atestado", ficaiParticipa: "SIM" }); expect(result).toBe(44); expect(dbMocks.createAbsence).toHaveBeenCalledWith(expect.objectContaining({ alunoId: 7, escolaId: 2, registradoPor: 88, ficaiParticipa: "SIM" })); });
  it("blocks a school user from writing into another unit", async () => { dbMocks.getBusinessUser.mockResolvedValue({ id: 89, perfil: "ESCOLA", escolaId: 2, ativo: 1 }); await expect(appRouter.createCaller(context("user", 9)).absences.create({ alunoId: 7, escolaId: 3, dataFalta: "2026-08-26", quantidadeDias: 1, motivo: "Doença" })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dbMocks.createAbsence).not.toHaveBeenCalled(); });
  it("creates, lists and reviews a submission using the exact workflow states", async () => { const caller = appRouter.createCaller(context("admin")); await caller.submissions.create({ escolaId: 2, periodo: "Agosto de 2026" }); const listed = await caller.submissions.list(); await caller.submissions.review({ id: 55, status: "APROVADO", observacaoAdmin: "Conferido pela secretaria" }); expect(dbMocks.createSubmission).toHaveBeenCalledWith(expect.objectContaining({ escolaId: 2, periodo: "2026-08", usuarioId: 88 }), undefined); expect(listed[0]?.status).toBe("ENVIADO"); expect(dbMocks.reviewSubmission).toHaveBeenCalledWith(expect.objectContaining({ id: 55, status: "APROVADO", observacaoAdmin: "Conferido pela secretaria" })); });
  it("rejects empty periods before any submission is persisted", async () => { await expect(appRouter.createCaller(context("admin")).submissions.create({ escolaId: 2, periodo: "" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(dbMocks.createSubmission).not.toHaveBeenCalled(); });
  it("does not persist an import until the explicit confirm procedure is called", async () => { const caller = appRouter.createCaller(context("admin")); expect(dbMocks.confirmStudentImport).not.toHaveBeenCalled(); await caller.imports.confirm({ escola: "CEI LUIZ FELIPE", students: [] }); expect(dbMocks.confirmStudentImport).toHaveBeenCalledWith({ escolaId: 2, students: [] }); });
});
