import { describe, expect, it } from "vitest";
import { detectSchoolHeader, markDuplicateStudents, parseImportText, parseStudentBlocks } from "../shared/pdfParser";

describe("parseStudentBlocks", () => {
  const text = `Escola: CEI LUIZ FELIPE\n\n001 ABNER GAEL DE ALMEIDA DE OLIVEIRA\n224837010278\nMATERNAL II - B\n00096\n21/12/2025\n\nFiliação 1:\nGRACIELLY BARRETO\n\nFiliação 2:\nAELCIO MOREIRA\n\nRespons:\nGRACIELLY BARRETO\n\nFone 1:\n(66)99920-5038\n\nFone 2:\n(66)99649-1023\n\n002 ALICE ROCHA MEDEIROS\n224837010279\nMATERNAL II - C\n00097\n21/12/2025\n\nRespons:\nMARIA ROCHA\n\nFone 1:\n(66)99999-0000`;
  it("keeps each student block independent and extracts labeled fields", () => { const result = parseStudentBlocks(text); expect(result).toHaveLength(2); expect(result[0]).toMatchObject({ nome: "ABNER GAEL DE ALMEIDA DE OLIVEIRA", turma: "MATERNAL II - B", matricula: "00096", responsavel: "GRACIELLY BARRETO", fone2: "(66)99649-1023", status: "OK" }); expect(result[1]).toMatchObject({ nome: "ALICE ROCHA MEDEIROS", turma: "MATERNAL II - C", matricula: "00097", responsavel: "MARIA ROCHA", fone2: "" }); });
  it("identifies the school header and returns a structured import", () => { expect(detectSchoolHeader(text)).toBe("CEI LUIZ FELIPE"); expect(parseImportText(text).alunos).toHaveLength(2); });
  it("keeps missing values empty and reports an alert instead of inventing data", () => { const [student] = parseStudentBlocks("001 ALUNO SEM RESPONSAVEL\n123456789\nMATERNAL II - A\n00001"); expect(student.responsavel).toBe(""); expect(student.alertas).toContain("Responsável não informado"); expect(student.status).toBe("ATENCAO"); });
  it("marks duplicates by school-level matricula or INEP", () => { const [student] = parseStudentBlocks("001 ALUNO DUPLICADO\n123456789\nMATERNAL II - A\n00001"); const [marked] = markDuplicateStudents(student ? [student] : [], [{ matricula: "00001", inep: null }]); expect(marked.duplicate).toBe(true); expect(marked.alertas).toContain("Possível duplicidade: matrícula ou INEP já cadastrado"); });
});
