export type ParsedStudent = { nome: string; inep: string; turma: string; matricula: string; dataMatricula: string; filiacao1: string; filiacao2: string; responsavel: string; fone1: string; fone2: string; endereco: string; status: "OK" | "ATENCAO" | "ERRO"; alertas: string[]; duplicate?: boolean };
export type ParsedImport = { escola: string; alunos: ParsedStudent[] };
const clean = (value: string | undefined) => (value ?? "").replace(/\s+/g, " ").trim();
const valueAfter = (block: string, label: string, nextLabels: string[]) => { const ending = nextLabels.length ? `(?=\\n\\s*(?:${nextLabels.join("|")})\\s*:?)` : "$"; const pattern = new RegExp(`${label}\\s*:?\\s*([\\s\\S]*?)${ending}`, "i"); return clean(block.match(pattern)?.[1]); };

export function detectSchoolHeader(rawText: string) { return clean(rawText.match(/(?:^|\n)\s*Escola\s*:\s*([^\n]+)/i)?.[1]); }
export function parseStudentBlocks(rawText: string): ParsedStudent[] {
  const normalized = rawText.replace(/\r/g, "");
  const starts = Array.from(normalized.matchAll(/(?:^|\n)\s*\d{1,5}\s+([^\n]+)\n(?=\s*\d{6,})/g)).map(match => match.index === undefined ? 0 : match.index + (match[0].startsWith("\n") ? 1 : 0));
  const blocks = starts.map((start, index) => normalized.slice(start, starts[index + 1] ?? normalized.length).trim()).filter(Boolean);
  return blocks.map(block => {
    const lines = block.split("\n").map(clean).filter(Boolean); const first = lines[0] ?? ""; const nome = clean(first.replace(/^\d{1,5}\s+/, "")); const inep = clean(lines.find(line => /^\d{9,20}$/.test(line))); const turma = clean(lines.find(line => /^(?:BERÇÁRIO|MATERNAL|PRE|PRÉ|JARDIM|1º|2º|3º|4º|5º|[A-Z].*\s-\s[A-Z0-9])/.test(line) && !/^\d/.test(line))); const matricula = clean(lines.find((line, index) => /^\d{3,8}$/.test(line) && index > 0 && line !== inep)); const dataMatricula = clean(lines.find(line => /^\d{2}\/\d{2}\/\d{4}$/.test(line))); const labels = ["Filiação 1", "Filiação 2", "Respons", "Fone 1", "Fone 2", "Endereço"]; const filiacao1 = valueAfter(block, "Filiação 1", labels.slice(1)); const filiacao2 = valueAfter(block, "Filiação 2", labels.slice(2)); const responsavel = valueAfter(block, "Respons", labels.slice(3)); const fone1 = valueAfter(block, "Fone 1", labels.slice(4)); const fone2 = valueAfter(block, "Fone 2", []); const endereco = valueAfter(block, "Endereço", []); const alertas: string[] = []; if (!nome) alertas.push("Nome não identificado"); if (!turma) alertas.push("Turma não identificada"); if (!matricula) alertas.push("Matrícula não identificada"); if (!responsavel) alertas.push("Responsável não informado"); return { nome, inep, turma, matricula, dataMatricula, filiacao1, filiacao2, responsavel, fone1, fone2, endereco, alertas, status: alertas.some(alerta => /Nome|Turma|Matrícula/.test(alerta)) ? "ERRO" : alertas.length ? "ATENCAO" : "OK" };
  });
}
export function parseImportText(rawText: string): ParsedImport { return { escola: detectSchoolHeader(rawText), alunos: parseStudentBlocks(rawText) }; }
export function markDuplicateStudents(students: ParsedStudent[], existing: Array<{ matricula: string; inep: string | null }>) { const matriculas = new Set(existing.map(student => student.matricula).filter(Boolean)); const inepps = new Set(existing.map(student => student.inep).filter(Boolean)); return students.map(student => { const duplicate = (!!student.matricula && matriculas.has(student.matricula)) || (!!student.inep && inepps.has(student.inep)); return duplicate ? { ...student, duplicate: true, alertas: [...student.alertas, "Possível duplicidade: matrícula ou INEP já cadastrado"], status: "ATENCAO" as const } : student; }); }
